### ISSUE TITLE
G29 - Préparer mon environnement de travail  (IDE, BD) ainsi qu'effectuer des recherches sur les bonnes pratique de développement avec les technologies choisies par mon équipe.

### ISSUE THREAD

**Issue by DulceCayetano** [gti525/h18-analytique-back#7]

**Comment by Haedy** [comment]
POur le Java je propose IntelliJ IDEA qui a une version gratuite pour etudiant

**Comment by MarcantVez** [comment]
@Haedy J'approuve à 110% pour IntelliJ, mais la version Ultimate...
En plus, avec vos courriels ets vous avez accès à vous créer un compte étudiant et obtenir la version ultimate gratuite. 
Tu peux même configurer une DataSource pour consulter la base de donnée à même ton IDE, faire du SQL, avoir le support pour Spring Boot, etc.

comparaison des versions:
https://www.jetbrains.com/idea/features/editions_comparison_matrix.html
